[project]
name = "deal-hunter-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "flask-cors>=6.0.5",
    "flask-openapi3[swagger,swagger-ui]>=4.3.2",
    "flask-sqlalchemy>=3.1.1",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
